<? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
<? $this->headScript()->appendFile('facets.js'); ?>
<? $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
<? if (!in_array($title, $collapsedFacets)): ?>
  <?
  $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
  ?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<? else: ?>
  <?
  $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
  ?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<? endif; ?>
<li id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
    data-facet="<?=$this->escapeHtmlAttr($title)?>"
    data-path="<?=$this->currentPath()?>"
    data-exclude="<?=$allowExclude?>"
    data-operator="<?=$this->recommend->getFacetOperator($title)?>"
    data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
    data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
</li>