<?
  if(strlen($facet['displayText']) == 0) {
    $facet['displayText'] = "-";
  }
?>
<? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
<? if ($i == 6): ?>
  <a id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($title)?>" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('more')?> ...</a>
<? endif; ?>
<? if ($facet['isApplied']): ?>
  <a class="list-group-item active<? if ($i>5): ?><?=$moreClass ?><?endif ?><? if ($facet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $facet['value'], true, $facet['operator']) ?>">
    <? if ($facet['operator'] == 'OR'): ?>
      <i class="fa fa-check-square-o"></i>
    <? else: ?>
      <span class="pull-right"><i class="fa fa-check"></i></span>
    <? endif; ?>
    <?=$this->escapeHtml($facet['displayText'])?>
  </a>
<? else: ?>
  <?
    $addURL = $this->currentPath().$results->getUrlQuery()->addFacet($title, $facet['value'], $facet['operator']);
    $badge = '<span class="badge">' . $this->localizedNumber($facet['count']);
    if ($allowExclude) {
      $badge .= '<a href="'.$this->currentPath().$results->getUrlQuery()->addFacet($title, $facet['value'], 'NOT')
        . '" title="'.$this->transEsc('exclude_facet').'"><i class="fa fa-times"></i></a>';
    }
    $badge .= '</span>';
    $classes = 'list-group-item facet'.$facet['operator'];
    if ($i>5) $classes .= ' ' . $moreClass;
  ?>
  <? if ($allowExclude): ?>
    <div class="<?=$classes ?>">
      <?=$badge ?>
      <a href="<?=$addURL ?>">
        <? if($facet['operator'] == 'OR'): ?><i class="fa fa-square-o"></i><? endif; ?>
        <?=$this->escapeHtml($facet['displayText'])?>
      </a>
    </div>
  <? else: ?>
    <a href="<?=$addURL ?>" class="<?=$classes ?>">
      <?=$badge ?>
      <? if($facet['operator'] == 'OR'): ?><i class="fa fa-square-o"></i><? endif; ?>
      <?=$this->escapeHtml($facet['displayText'])?>
    </a>
  <? endif; ?>
<? endif; ?>