<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
<?
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown ++;
    }
    $html .= '"><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''.($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label>';
  }
?>
  <div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>"><?=$html ?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
  <ul class="list-group filters">
    <li class="list-group-item title"><?=$this->transEsc('Remove Filters')?></li>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </ul>
<? endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <ul class="list-group facet" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <li class="list-group-item title<? if(!empty($collapsedFacets)): ?><? if(in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?><? endif; ?>">
        <?=$this->transEsc($cluster['label'])?>
      </li>
      <?
        $listClasses = ['facet-list'];
        if (!empty($collapsedFacets)) {
          $listClasses[] = 'collapse';
          if (!in_array($title, $collapsedFacets)) {
            $listClasses[] = 'in';
          }
        }
      ?>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="<?=implode(' ', $listClasses) ?>">
        <? if (isset($rangeFacets[$title])): ?>
          <?=$this->context()->renderInContext('Recommend/SideFacets/range-facet.phtml', ['rangeFacets'=>$rangeFacets, 'title'=>$title, ]); ?>
        <? else: ?>
          <? if (in_array($title, $hierarchicalFacets)): ?>
            <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
            <? $this->headScript()->appendFile('facets.js'); ?>
            <? $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
            <? if (!in_array($title, $collapsedFacets)): ?>
              <?
              $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
              ?>
              <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <? else: ?>
              <?
              $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
              ?>
              <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <? endif; ?>
            <li id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
                  data-facet="<?=$this->escapeHtmlAttr($title)?>"
                  data-path="<?=$this->currentPath()?>"
                  data-exclude="<?=$allowExclude?>"
                  data-operator="<?=$this->recommend->getFacetOperator($title)?>"
                  data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
                  data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
            </li>
            <noscript>
          <? endif; ?>
          <? foreach ($cluster['list'] as $i=>$thisFacet): ?>
              <?
                if(strlen($thisFacet['displayText']) == 0) {
                  $thisFacet['displayText'] = "-";
                }
              ?>
              <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
            <? if ($i == 6): ?>
              <a id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($title)?>" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('more')?> ...</a>
            <? endif; ?>
            <? if ($thisFacet['isApplied']): ?>
              <a class="list-group-item active<? if ($i>5): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?>">
                <? if ($thisFacet['operator'] == 'OR'): ?>
                  <i class="fa fa-check-square-o"></i>
                <? else: ?>
                  <span class="pull-right"><i class="fa fa-check"></i></span>
                <? endif; ?>
                <?=$this->escapeHtml($thisFacet['displayText'])?>
              </a>
            <? else: ?>
              <? $addURL = $this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
              <? if ($allowExclude): ?>
                <li class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i>5): ?> <?=$moreClass ?><?endif ?>">
              <? else: ?>
                <a href="<?=$addURL ?>" class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i>5): ?> <?=$moreClass ?><?endif ?>">
              <? endif; ?>
              <span class="badge">
                <?=$this->localizedNumber($thisFacet['count'])?>
                <? if ($allowExclude): ?>
                  <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times"></i></a>
                <? endif; ?>
              </span>
              <? if ($allowExclude): ?>
                <a href="<?=$addURL ?>">
              <? endif; ?>
              <? if($thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-square-o"></i>
              <? endif; ?>
              <?=$this->escapeHtml($thisFacet['displayText'])?>
              <? if ($allowExclude): ?>
                  </a>
                </li>
              <? else: ?>
                </a>
              <? endif; ?>
            <? endif; ?>
          <? endforeach; ?>
          <? if ($i > 5): ?><a class="list-group-item <?=$moreClass ?>" href="javascript:lessFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('less')?> ...</a><? endif; ?>
        <? endif; ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
          </noscript>
        <? endif; ?>
      </div>
    </ul>
  <? endforeach; ?>
<? endif; ?>