<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
<?
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown ++;
    }
    $html .= '"><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''.($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label>';
  }
?>
  <div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>"><?=$html ?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<? if (!empty($filterList)): ?>
  <div class="list-group filters">
    <div class="list-group-item title"><?=$this->transEsc('Remove Filters')?></div>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
            unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
<?=isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <div class="list-group facet" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <div class="list-group-item title<? if(!empty($collapsedFacets)): ?><? if(in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?><? endif; ?>">
        <?=$this->transEsc($cluster['label'])?>
      </div>
      <?
        $listClasses = ['facet-list'];
        if (!empty($collapsedFacets)) {
          $listClasses[] = 'collapse';
          if (!in_array($title, $collapsedFacets)) {
            $listClasses[] = 'in';
          }
        }
      ?>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="<?=implode(' ', $listClasses) ?>">
        <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
        <? if (isset($rangeFacets[$title])): ?>
          <?=$this->context()->renderInContext('Recommend/SideFacets/range.phtml', [
            'rangeFacets'=>$rangeFacets,
            'title'=>$title
          ]); ?>
        <? else: ?>
          <? if (in_array($title, $hierarchicalFacets)): ?>
            <?=$this->context()->renderInContext('Recommend/SideFacets/hierarchical.phtml', [
              'allowExclude'=>$allowExclude,
              'collapsedFacets'=>$collapsedFacets,
              'hierarchicalFacetSortOptions'=>$hierarchicalFacetSortOptions,
              'title'=>$title
            ]); ?>
            <noscript>
          <? endif; ?>
          <?=$this->context()->renderInContext('Recommend/SideFacets/render-list.phtml', [
            'allowExclude'=>$allowExclude,
            'cluster'=>$cluster,
            'facet'=>$thisFacet,
            'results'=>$results,
            'title'=>$title
          ]); ?>
        <? endif; ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
          </noscript>
        <? endif; ?>
      </div>
    </div>
  <? endforeach; ?>
<? endif; ?>